# Generated by Django 5.2.4 on 2025-07-14 13:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва товару')),
                ('description', models.TextField(verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Зображення')),
                ('category', models.CharField(max_length=100, verbose_name='Категорія')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('power', models.CharField(blank=True, max_length=50, verbose_name='Потужність')),
                ('efficiency', models.CharField(blank=True, max_length=50, verbose_name='Ефективність')),
                ('warranty', models.CharField(blank=True, max_length=50, verbose_name='Гарантія')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Країна виробника')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наявності')),
                ('featured', models.BooleanField(default=False, verbose_name='Рекомендований')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['-created_at'],
            },
        ),
    ]
