# Generated by Django 5.2.4 on 2025-07-16 10:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва проєкту')),
                ('description', models.TextField(verbose_name='Опис проєкту')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='Головне зображення')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Місце розташування')),
                ('power_capacity', models.CharField(blank=True, max_length=50, verbose_name='Потужність станції')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Дата завершення')),
                ('project_type', models.CharField(blank=True, max_length=100, verbose_name='Тип проєкту')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Клієнт')),
                ('featured', models.BooleanField(default=False, verbose_name='Рекомендований')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Проєкт портфоліо',
                'verbose_name_plural': 'Проєкти портфоліо',
                'ordering': ['-completion_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name="Ім'я клієнта")),
                ('client_position', models.CharField(blank=True, max_length=200, verbose_name='Посада/компанія')),
                ('review_text', models.TextField(verbose_name='Текст відгуку')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оцінка')),
                ('project_type', models.CharField(blank=True, max_length=100, verbose_name='Тип проєкту')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Місце проєкту')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-created_at'],
            },
        ),
    ]
