# Generated by Django 5.2.4 on 2025-07-19 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_add_category_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.brand', verbose_name='Новий бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='new_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Нова категорія'),
        ),
    ]
