# Generated by Django 5.2.4 on 2025-07-19 06:36

from django.db import migrations
from django.db import models


def transfer_data(apps, schema_editor):
    """Переносимо дані з new_category та new_brand в new_category_fk та new_brand_fk"""
    Product = apps.get_model('mainapp', 'Product')
    
    for product in Product.objects.all():
        if product.new_category:
            product.new_category_fk = product.new_category
        if product.new_brand:
            product.new_brand_fk = product.new_brand
        product.save()


def reverse_transfer_data(apps, schema_editor):
    """Зворотне перенесення даних"""
    pass  # Не можемо повернути тестові дані назад


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_add_temp_fk_fields'),
    ]

    operations = [
        # Спочатку додаємо нові поля ForeignKey
        migrations.AddField(
            model_name='product',
            name='new_category_fk',
            field=models.ForeignKey(
                null=True, blank=True,
                on_delete=models.CASCADE,
                to='mainapp.category',
                verbose_name='Нова категорія'
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='new_brand_fk',
            field=models.ForeignKey(
                null=True, blank=True,
                on_delete=models.CASCADE,
                to='mainapp.brand',
                verbose_name='Новий бренд'
            ),
        ),
        
        # Переносимо дані
        migrations.RunPython(transfer_data, reverse_transfer_data),
        
        # Видаляємо старі поля
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='new_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='new_brand',
        ),
        
        # Перейменовуємо нові поля
        migrations.RenameField(
            model_name='product',
            old_name='new_category_fk',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='new_brand_fk',
            new_name='brand',
        ),
        
        # Робимо поля обов'язковими
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                to='mainapp.category',
                verbose_name='Категорія'
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                to='mainapp.brand',
                verbose_name='Бренд'
            ),
        ),
    ]
